/* 
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace WebApplication1.ApiModel
{
    /// <summary>
    /// Information about processing of the application.
    /// </summary>
    [DataContract]
        public partial class BadgeApplicationProcess :  IEquatable<BadgeApplicationProcess>, IValidatableObject
    {
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum StatusEnum
        {
            /// <summary>
            /// Enum REQUESTED for value: REQUESTED
            /// </summary>
            [EnumMember(Value = "REQUESTED")]
            REQUESTED = 0,
            /// <summary>
            /// Enum PROCESSED for value: PROCESSED
            /// </summary>
            [EnumMember(Value = "PROCESSED")]
            PROCESSED = 1,
            /// <summary>
            /// Enum DECLINED for value: DECLINED
            /// </summary>
            [EnumMember(Value = "DECLINED")]
            DECLINED = 2        }
        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="BadgeApplicationProcess" /> class.
        /// </summary>
        /// <param name="status">status (required).</param>
        /// <param name="rejectionReasons">A list of rejection reasons for the badge application. Returned for process.status &#x3D; DECLINED only. (required).</param>
        public BadgeApplicationProcess(StatusEnum status = default(StatusEnum), List<BadgeApplicationRejectionReason> rejectionReasons = default(List<BadgeApplicationRejectionReason>))
        {
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new InvalidDataException("status is a required property for BadgeApplicationProcess and cannot be null");
            }
            else
            {
                this.Status = status;
            }
            // to ensure "rejectionReasons" is required (not null)
            if (rejectionReasons == null)
            {
                throw new InvalidDataException("rejectionReasons is a required property for BadgeApplicationProcess and cannot be null");
            }
            else
            {
                this.RejectionReasons = rejectionReasons;
            }
        }
        

        /// <summary>
        /// A list of rejection reasons for the badge application. Returned for process.status &#x3D; DECLINED only.
        /// </summary>
        /// <value>A list of rejection reasons for the badge application. Returned for process.status &#x3D; DECLINED only.</value>
        [DataMember(Name="rejectionReasons", EmitDefaultValue=false)]
        public List<BadgeApplicationRejectionReason> RejectionReasons { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BadgeApplicationProcess {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  RejectionReasons: ").Append(RejectionReasons).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BadgeApplicationProcess);
        }

        /// <summary>
        /// Returns true if BadgeApplicationProcess instances are equal
        /// </summary>
        /// <param name="input">Instance of BadgeApplicationProcess to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BadgeApplicationProcess input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.RejectionReasons == input.RejectionReasons ||
                    this.RejectionReasons != null &&
                    input.RejectionReasons != null &&
                    this.RejectionReasons.SequenceEqual(input.RejectionReasons)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.RejectionReasons != null)
                    hashCode = hashCode * 59 + this.RejectionReasons.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
