/* 
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace WebApplication1.ApiModel
{
    /// <summary>
    /// Payment provider
    /// </summary>
    /// <value>Payment provider</value>
        public enum CheckoutFormPaymentProvider
    {
        /// <summary>
        /// Enum P24 for value: P24
        /// </summary>
        
        P24,
        /// <summary>
        /// Enum PAYU for value: PAYU
        /// </summary>
        
        PAYU    }
}
