/* 
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace WebApplication1.ApiModel
{
    /// <summary>
    /// Payment type
    /// </summary>
    /// <value>Payment type</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum CheckoutFormPaymentType
    {
        /// <summary>
        /// Enum CASHONDELIVERY for value: CASH_ON_DELIVERY
        /// </summary>
        [EnumMember(Value = "CASH_ON_DELIVERY")]
        CASHONDELIVERY = 0,
        /// <summary>
        /// Enum WIRETRANSFER for value: WIRE_TRANSFER
        /// </summary>
        [EnumMember(Value = "WIRE_TRANSFER")]
        WIRETRANSFER = 1,
        /// <summary>
        /// Enum ONLINE for value: ONLINE
        /// </summary>
        [EnumMember(Value = "ONLINE")]
        ONLINE = 2    }
}
