/* 
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace WebApplication1.ApiModel
{
    /// <summary>
    /// InitializeRefund
    /// </summary>
    [DataContract]
        public partial class InitializeRefund :  IEquatable<InitializeRefund>, IValidatableObject
    {
        /// <summary>
        /// Reason for a payment refund.
        /// </summary>
        /// <value>Reason for a payment refund.</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum ReasonEnum
        {
            /// <summary>
            /// Enum REFUND for value: REFUND
            /// </summary>
            [EnumMember(Value = "REFUND")]
            REFUND = 0,
            /// <summary>
            /// Enum COMPLAINT for value: COMPLAINT
            /// </summary>
            [EnumMember(Value = "COMPLAINT")]
            COMPLAINT = 1,
            /// <summary>
            /// Enum PRODUCTNOTAVAILABLE for value: PRODUCT_NOT_AVAILABLE
            /// </summary>
            [EnumMember(Value = "PRODUCT_NOT_AVAILABLE")]
            PRODUCTNOTAVAILABLE = 2,
            /// <summary>
            /// Enum PAIDVALUETOOLOW for value: PAID_VALUE_TOO_LOW
            /// </summary>
            [EnumMember(Value = "PAID_VALUE_TOO_LOW")]
            PAIDVALUETOOLOW = 3        }
        /// <summary>
        /// Reason for a payment refund.
        /// </summary>
        /// <value>Reason for a payment refund.</value>
        [DataMember(Name="reason", EmitDefaultValue=false)]
        public ReasonEnum Reason { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="InitializeRefund" /> class.
        /// </summary>
        /// <param name="payment">payment (required).</param>
        /// <param name="reason">Reason for a payment refund. (required).</param>
        /// <param name="lineItems">List of order&#x27;s line items which can be refunded..</param>
        /// <param name="delivery">delivery.</param>
        /// <param name="overpaid">overpaid.</param>
        /// <param name="surcharges">List of surcharges for payment which can be refunded..</param>
        /// <param name="additionalServices">additionalServices.</param>
        public InitializeRefund(RefundPayment payment = default(RefundPayment), ReasonEnum reason = default(ReasonEnum), List<RefundLineItem> lineItems = default(List<RefundLineItem>), InitializeRefundDelivery delivery = default(InitializeRefundDelivery), InitializeRefundOverpaid overpaid = default(InitializeRefundOverpaid), List<PaymentsSurcharge> surcharges = default(List<PaymentsSurcharge>), InitializeRefundAdditionalServices additionalServices = default(InitializeRefundAdditionalServices))
        {
            // to ensure "payment" is required (not null)
            if (payment == null)
            {
                throw new InvalidDataException("payment is a required property for InitializeRefund and cannot be null");
            }
            else
            {
                this.Payment = payment;
            }
            // to ensure "reason" is required (not null)
            if (reason == null)
            {
                throw new InvalidDataException("reason is a required property for InitializeRefund and cannot be null");
            }
            else
            {
                this.Reason = reason;
            }
            this.LineItems = lineItems;
            this.Delivery = delivery;
            this.Overpaid = overpaid;
            this.Surcharges = surcharges;
            this.AdditionalServices = additionalServices;
        }
        
        /// <summary>
        /// Gets or Sets Payment
        /// </summary>
        [DataMember(Name="payment", EmitDefaultValue=false)]
        public RefundPayment Payment { get; set; }


        /// <summary>
        /// List of order&#x27;s line items which can be refunded.
        /// </summary>
        /// <value>List of order&#x27;s line items which can be refunded.</value>
        [DataMember(Name="lineItems", EmitDefaultValue=false)]
        public List<RefundLineItem> LineItems { get; set; }

        /// <summary>
        /// Gets or Sets Delivery
        /// </summary>
        [DataMember(Name="delivery", EmitDefaultValue=false)]
        public InitializeRefundDelivery Delivery { get; set; }

        /// <summary>
        /// Gets or Sets Overpaid
        /// </summary>
        [DataMember(Name="overpaid", EmitDefaultValue=false)]
        public InitializeRefundOverpaid Overpaid { get; set; }

        /// <summary>
        /// List of surcharges for payment which can be refunded.
        /// </summary>
        /// <value>List of surcharges for payment which can be refunded.</value>
        [DataMember(Name="surcharges", EmitDefaultValue=false)]
        public List<PaymentsSurcharge> Surcharges { get; set; }

        /// <summary>
        /// Gets or Sets AdditionalServices
        /// </summary>
        [DataMember(Name="additionalServices", EmitDefaultValue=false)]
        public InitializeRefundAdditionalServices AdditionalServices { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InitializeRefund {\n");
            sb.Append("  Payment: ").Append(Payment).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  LineItems: ").Append(LineItems).Append("\n");
            sb.Append("  Delivery: ").Append(Delivery).Append("\n");
            sb.Append("  Overpaid: ").Append(Overpaid).Append("\n");
            sb.Append("  Surcharges: ").Append(Surcharges).Append("\n");
            sb.Append("  AdditionalServices: ").Append(AdditionalServices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InitializeRefund);
        }

        /// <summary>
        /// Returns true if InitializeRefund instances are equal
        /// </summary>
        /// <param name="input">Instance of InitializeRefund to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InitializeRefund input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Payment == input.Payment ||
                    (this.Payment != null &&
                    this.Payment.Equals(input.Payment))
                ) && 
                (
                    this.Reason == input.Reason ||
                    (this.Reason != null &&
                    this.Reason.Equals(input.Reason))
                ) && 
                (
                    this.LineItems == input.LineItems ||
                    this.LineItems != null &&
                    input.LineItems != null &&
                    this.LineItems.SequenceEqual(input.LineItems)
                ) && 
                (
                    this.Delivery == input.Delivery ||
                    (this.Delivery != null &&
                    this.Delivery.Equals(input.Delivery))
                ) && 
                (
                    this.Overpaid == input.Overpaid ||
                    (this.Overpaid != null &&
                    this.Overpaid.Equals(input.Overpaid))
                ) && 
                (
                    this.Surcharges == input.Surcharges ||
                    this.Surcharges != null &&
                    input.Surcharges != null &&
                    this.Surcharges.SequenceEqual(input.Surcharges)
                ) && 
                (
                    this.AdditionalServices == input.AdditionalServices ||
                    (this.AdditionalServices != null &&
                    this.AdditionalServices.Equals(input.AdditionalServices))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Payment != null)
                    hashCode = hashCode * 59 + this.Payment.GetHashCode();
                if (this.Reason != null)
                    hashCode = hashCode * 59 + this.Reason.GetHashCode();
                if (this.LineItems != null)
                    hashCode = hashCode * 59 + this.LineItems.GetHashCode();
                if (this.Delivery != null)
                    hashCode = hashCode * 59 + this.Delivery.GetHashCode();
                if (this.Overpaid != null)
                    hashCode = hashCode * 59 + this.Overpaid.GetHashCode();
                if (this.Surcharges != null)
                    hashCode = hashCode * 59 + this.Surcharges.GetHashCode();
                if (this.AdditionalServices != null)
                    hashCode = hashCode * 59 + this.AdditionalServices.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
