/* 
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace WebApplication1.ApiModel
{
    /// <summary>
    /// The processing status of the command.
    /// </summary>
    /// <value>The processing status of the command.</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum ProcessingStatus
    {
        /// <summary>
        /// Enum QUEUEING for value: QUEUEING
        /// </summary>
        [EnumMember(Value = "QUEUEING")]
        QUEUEING = 0,
        /// <summary>
        /// Enum RUNNING for value: RUNNING
        /// </summary>
        [EnumMember(Value = "RUNNING")]
        RUNNING = 1,
        /// <summary>
        /// Enum VALIDATEDANDRUNNING for value: VALIDATED_AND_RUNNING
        /// </summary>
        [EnumMember(Value = "VALIDATED_AND_RUNNING")]
        VALIDATEDANDRUNNING = 2,
        /// <summary>
        /// Enum RUNNINGBUTWITHERRORS for value: RUNNING_BUT_WITH_ERRORS
        /// </summary>
        [EnumMember(Value = "RUNNING_BUT_WITH_ERRORS")]
        RUNNINGBUTWITHERRORS = 3,
        /// <summary>
        /// Enum SUCCESSFUL for value: SUCCESSFUL
        /// </summary>
        [EnumMember(Value = "SUCCESSFUL")]
        SUCCESSFUL = 4,
        /// <summary>
        /// Enum PARTIALSUCCESS for value: PARTIAL_SUCCESS
        /// </summary>
        [EnumMember(Value = "PARTIAL_SUCCESS")]
        PARTIALSUCCESS = 5,
        /// <summary>
        /// Enum ERROR for value: ERROR
        /// </summary>
        [EnumMember(Value = "ERROR")]
        ERROR = 6    }
}
