/* 
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace WebApplication1.ApiModel
{
    /// <summary>
    /// PromotionCampaignResponseDto
    /// </summary>
    [DataContract]
        public partial class PromotionCampaignResponseDto :  IEquatable<PromotionCampaignResponseDto>, IValidatableObject
    {
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum StatusEnum
        {
            /// <summary>
            /// Enum REQUESTED for value: REQUESTED
            /// </summary>
            [EnumMember(Value = "REQUESTED")]
            REQUESTED = 0,
            /// <summary>
            /// Enum SUSPENDED for value: SUSPENDED
            /// </summary>
            [EnumMember(Value = "SUSPENDED")]
            SUSPENDED = 1,
            /// <summary>
            /// Enum VERIFICATION for value: VERIFICATION
            /// </summary>
            [EnumMember(Value = "VERIFICATION")]
            VERIFICATION = 2,
            /// <summary>
            /// Enum ACCEPTED for value: ACCEPTED
            /// </summary>
            [EnumMember(Value = "ACCEPTED")]
            ACCEPTED = 3,
            /// <summary>
            /// Enum ACTIVE for value: ACTIVE
            /// </summary>
            [EnumMember(Value = "ACTIVE")]
            ACTIVE = 4,
            /// <summary>
            /// Enum FINISHED for value: FINISHED
            /// </summary>
            [EnumMember(Value = "FINISHED")]
            FINISHED = 5,
            /// <summary>
            /// Enum DECLINED for value: DECLINED
            /// </summary>
            [EnumMember(Value = "DECLINED")]
            DECLINED = 6        }
        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PromotionCampaignResponseDto" /> class.
        /// </summary>
        /// <param name="campaign">campaign (required).</param>
        /// <param name="link">link (required).</param>
        /// <param name="promotion">promotion (required).</param>
        /// <param name="status">status (required).</param>
        public PromotionCampaignResponseDto(CampaignResponseDto campaign = default(CampaignResponseDto), string link = default(string), PromotionResponseDto promotion = default(PromotionResponseDto), StatusEnum status = default(StatusEnum))
        {
            // to ensure "campaign" is required (not null)
            if (campaign == null)
            {
                throw new InvalidDataException("campaign is a required property for PromotionCampaignResponseDto and cannot be null");
            }
            else
            {
                this.Campaign = campaign;
            }
            // to ensure "link" is required (not null)
            if (link == null)
            {
                throw new InvalidDataException("link is a required property for PromotionCampaignResponseDto and cannot be null");
            }
            else
            {
                this.Link = link;
            }
            // to ensure "promotion" is required (not null)
            if (promotion == null)
            {
                throw new InvalidDataException("promotion is a required property for PromotionCampaignResponseDto and cannot be null");
            }
            else
            {
                this.Promotion = promotion;
            }
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new InvalidDataException("status is a required property for PromotionCampaignResponseDto and cannot be null");
            }
            else
            {
                this.Status = status;
            }
        }
        
        /// <summary>
        /// Gets or Sets Campaign
        /// </summary>
        [DataMember(Name="campaign", EmitDefaultValue=false)]
        public CampaignResponseDto Campaign { get; set; }

        /// <summary>
        /// Gets or Sets Link
        /// </summary>
        [DataMember(Name="link", EmitDefaultValue=false)]
        public string Link { get; set; }

        /// <summary>
        /// Gets or Sets Promotion
        /// </summary>
        [DataMember(Name="promotion", EmitDefaultValue=false)]
        public PromotionResponseDto Promotion { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PromotionCampaignResponseDto {\n");
            sb.Append("  Campaign: ").Append(Campaign).Append("\n");
            sb.Append("  Link: ").Append(Link).Append("\n");
            sb.Append("  Promotion: ").Append(Promotion).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PromotionCampaignResponseDto);
        }

        /// <summary>
        /// Returns true if PromotionCampaignResponseDto instances are equal
        /// </summary>
        /// <param name="input">Instance of PromotionCampaignResponseDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PromotionCampaignResponseDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Campaign == input.Campaign ||
                    (this.Campaign != null &&
                    this.Campaign.Equals(input.Campaign))
                ) && 
                (
                    this.Link == input.Link ||
                    (this.Link != null &&
                    this.Link.Equals(input.Link))
                ) && 
                (
                    this.Promotion == input.Promotion ||
                    (this.Promotion != null &&
                    this.Promotion.Equals(input.Promotion))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Campaign != null)
                    hashCode = hashCode * 59 + this.Campaign.GetHashCode();
                if (this.Link != null)
                    hashCode = hashCode * 59 + this.Link.GetHashCode();
                if (this.Promotion != null)
                    hashCode = hashCode * 59 + this.Promotion.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
