/* 
 * Allegro REST API
 *
 * https://developer.allegro.pl/about
 *
 * OpenAPI spec version: latest
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace WebApplication1.ApiModel
{
    /// <summary>
    /// The selling format of the offer.
    /// </summary>
    /// <value>The selling format of the offer.</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum SellingModeFormat
    {
        /// <summary>
        /// Enum BUYNOW for value: BUY_NOW
        /// </summary>
        [EnumMember(Value = "BUY_NOW")]
        BUYNOW = 0,
        /// <summary>
        /// Enum AUCTION for value: AUCTION
        /// </summary>
        [EnumMember(Value = "AUCTION")]
        AUCTION = 1,
        /// <summary>
        /// Enum ADVERTISEMENT for value: ADVERTISEMENT
        /// </summary>
        [EnumMember(Value = "ADVERTISEMENT")]
        ADVERTISEMENT = 2    }
}
